  version: '2'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/home-assistant
      volumes:
        - /docker/homeassistant/:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host
